repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
        args: ['--allow-multiple-documents', '--unsafe']
      - id: end-of-file-fixer
        exclude_types: ['json']
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.17
    hooks:
      - id: actionlint-docker
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
  # - repo: https://github.com/ansible-community/ansible-lint.git
  #   rev: v6.5.2
  #   hooks:
  #     - id: ansible-lint
  - repo: local
    hooks:
      - id: packer_validate
        name: Packer Validate
        entry: scripts/packer-lint.sh validate
        language: system
        files: '.*pkr.*.hcl$'
      - id: packer_fmt
        name: Packer Format
        entry: scripts/packer-lint.sh fmt
        language: system
        files: '.*pkr.*.hcl$'
