
language: bash
env:
  - KS_VER=F23
before_install:
  - python --version
  - pip --version
install:
  - pip install --user six requests
  - git clone --depth 1 -b r2.20-1 git://github.com/rhinstaller/pykickstart.git
  - (cd pykickstart && pip install --user .)
  - chmod +x ./part.sh && ./part.sh
script:
  - ksvalidator --followincludes --version $KS_VER ./xfce-nfs.cfg
  - ksvalidator --followincludes --version $KS_VER ./xfce-git.cfg
