
language: python
python:
  - "3.6"
env:
  - KS_VER=F25
install:
  - pip install six requests
  - git clone --depth 1 -b r3.5-1 git://github.com/rhinstaller/pykickstart.git
  - (cd pykickstart && pip install .)
script:
  - ./scripts/partitions.sh test
  - ./scripts/vm-guests.sh --desktop --qemu --test
  - ksvalidator --followincludes --version $KS_VER ./repos.ks
  - ksvalidator --followincludes --version $KS_VER ./min.cfg
  - ksvalidator --followincludes --version $KS_VER ./base.cfg
  - ksvalidator --followincludes --version $KS_VER ./x-base.ks
  - ksvalidator --followincludes --version $KS_VER ./x-extras.ks
  - ksvalidator --followincludes --version $KS_VER ./x-applications.ks
  - ksvalidator --followincludes --version $KS_VER ./xfce-min.ks
  - ksvalidator --followincludes --version $KS_VER ./xfce.ks
  - ksvalidator --followincludes --version $KS_VER ./workstation.cfg
  - ksvalidator --followincludes --version $KS_VER ./kodi.ks
  - ksvalidator --followincludes --version $KS_VER ./htpc.cfg
