
language: python
env:
  - KS_VER=F23
install:
  - pip install six requests
  - git clone --depth 1 -b r2.20-1 git://github.com/rhinstaller/pykickstart.git
  - (cd pykickstart && pip install .)
script:
  - ./scripts/partitions.sh test
  - ./scripts/vm-guests.sh --desktop --qemu --test
  - ksvalidator --followincludes --version $KS_VER ./workstation.cfg
  - ksvalidator --followincludes --version $KS_VER ./htpc.cfg
