---
- name: Adding Flathub Flatpak Repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Installing Flatpaks
  community.general.flatpak:
    name: "{{ item }}"
  loop: "{{ flatpaks }}"
