---
# PRETASKS
- name: Removing Unneeded Packages
  ansible.builtin.dnf:
    autoremove: yes
- name: Upgrading Installed Packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
- name: Gathering Facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - 'hardware'
- name: Gathering Package Facts
  ansible.builtin.package_facts:
    manager: auto
- name: pyenv-module
  ansible.builtin.import_role:
    name: suzuki-shunsuke.pyenv-module

- ansible.builtin.include_tasks: repos.yml
- ansible.builtin.include_tasks: pkgs.yml
- ansible.builtin.include_tasks: cli.yml
- ansible.builtin.include_tasks: gui.yml
- ansible.builtin.include_tasks: flatpaks.yml
- ansible.builtin.include_tasks: chezmoi.yml
- ansible.builtin.include_tasks: users.yml
- name: Setting Up Python for Users
  ansible.builtin.include_tasks:
    file: pyenv.yml
    apply:
      become: yes
      become_user: "{{ item.name }}"
  vars:
  loop: "{{ user.results }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.item.get('pyenv') | bool
