---
- name: Resolve guest architecture for qemu
  ansible.builtin.set_fact:
    guest_arch: >-
      {{ lookup('env', 'GUEST_ARCH') |
      default('aarch64' if lookup('pipe', 'uname -m') in ['arm64', 'aarch64'] else 'x86_64',
      true) }}

- name: Resolve Lima instance and state paths
  ansible.builtin.set_fact:
    lima_instance_name: molecule-fedora-{{ fedora_version }}-{{ variant }}
    lima_template_path: /tmp/molecule-lima-{{ fedora_version }}-{{ variant }}.yaml
    lima_state_path: /tmp/molecule-lima-{{ fedora_version }}-{{ variant }}.state

- name: Include QEMU/KVM destroy tasks
  ansible.builtin.include_tasks: ../shared/instance-destroy-qemu-kvm.yml
  when: vm_platform == 'qemu-kvm'

- name: Include Lima destroy tasks
  ansible.builtin.include_tasks: ../shared/instance-destroy-lima.yml
  when: vm_platform == 'lima'
