---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
provisioner:
  name: ansible
  env:
    VM_PLATFORM: qemu
    VM_VARIANT: workstation
    VM_SSH_PORT: '2222'
  playbooks:
    create: ../shared/create.yml
    converge: ../shared/converge.yml
    destroy: ../shared/destroy.yml
  inventory:
    host_vars:
      instance:
        ansible_host: 127.0.0.1
        ansible_port: 2222
        ansible_user: root
        ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        vm_platform: qemu
        variant: workstation
verifier:
  name: ansible
  enabled: true
  playbooks:
    verify: ../shared/verify.yml
scenario:
  test_sequence:
    - create
    - converge
    - verify
    - destroy
