---
name: CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.sha }}
  cancel-in-progress: true

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: j178/prek-action@v2
